<a href="https://colab.research.google.com/github/js0805/solar_photovoltaics_prediction_-_analytics/blob/master/lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Develop LSTM model for solar PV power forecasting**

In [7]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

Data Preprocessing

In [8]:
def prepare_data(lstm_data, time_steps):
   x,y=[],[]
   for i in range(len(lstm_data)):
     #finding last element
     end_ix=i+time_steps
     if end_ix > len(lstm_data)-1:
       break
     seq_x,seq_y = lstm_data[i:end_ix], lstm_data[end_ix]
     x.append(seq_x)
     y.append(seq_y)
   return np.array(x), np.array(y)
  


In [14]:
data=pd.read_csv('/content/new.csv')
lstm_data= data['Energy'].to_numpy()
time_steps=7
x,y=prepare_data(lstm_data,time_steps)

In [19]:
print(x), print(y)

[[[483.]
  [371.]
  [551.]
  ...
  [491.]
  [547.]
  [564.]]

 [[371.]
  [551.]
  [614.]
  ...
  [547.]
  [564.]
  [546.]]

 [[551.]
  [614.]
  [491.]
  ...
  [564.]
  [546.]
  [518.]]

 ...

 [[712.]
  [609.]
  [607.]
  ...
  [573.]
  [652.]
  [668.]]

 [[609.]
  [607.]
  [639.]
  ...
  [652.]
  [668.]
  [627.]]

 [[607.]
  [639.]
  [573.]
  ...
  [668.]
  [627.]
  [592.]]]
[546.         518.          95.         476.         453.
 427.         617.         542.         464.         683.
 646.         597.         573.         515.         539.
 671.         659.         644.         681.         657.
 659.         717.         722.         701.         695.
 306.         325.         480.         470.         291.
 663.         599.         586.84615385 586.84615385 586.84615385
 586.84615385 586.84615385 583.         586.         243.
 464.         583.         617.         636.         591.
 507.         593.         587.         635.         602.
 620.         616.         609.   

(None, None)

In [16]:
x.shape

(360, 7)

In [17]:
z_axix=1
x=x.reshape((x.shape[0],x.shape[1],z_axix))


In [18]:
x.shape

(360, 7, 1)

**Building LSTM Model**

In [22]:
model = Sequential()
model.add(LSTM(50,activation = 'relu',return_sequences= True,input_shape=(time_steps, z_axix)))
model.add(LSTM(50,activation = 'relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss = 'mse')
model.fit(x,y, epochs =100,verbose=0)